print('3+4')
print(5+3)
print("Hello +word")
def  hello():
    print("hello")
    print("India")

hello()
print(2+3*5)
print((2+3)*5)
__init__=4
print(__init__)
ankitPal=6
print(ankitPal)
print(2**5)
print(8/4)
print(4+3j)
print(type(4+3j))
print(10_5000)
print(type(30.4))
print(type(0o1500))
print(0o67)
print(0b1000001)
print(oct(65))
print(hex(65))
print(bin(65))
print(oct(0x41))
print(hex(0x41))
print(0x41)
print(3.6)
print(type(3.6))
print(type(2e2))
print(2e2)
print(type(True))
print(False)
a=True
print(2+True)
b=False
print(2+False)
print(8>3)
print(2>3)
print(None)
print("hello7ujkword")
print("hello\"friends")
print('hello"friends')
print("Ankit'Pal")
print('Python\'s')
print("\"Hello\"")
print('"Hello"')
print('''Hello
      friends
      My Nmae is 
      Ankit pal''')
print("""Hello
      friends
      My Name is 
      Ankit Pal""")
print('\
      hi\
      friends \
      ')
print(len("hello"))
print(len("hello hi"))
print(len("hello\nhi"))
print("hello\qhi")
print(len("hello\qhi"))
print("m\f")
print("m\\f")
print("C:\new folder\text.txt")
print("C:\\new folder\\text.txt")
print('Python program')
print('python\'s program')
print("python\'s program")
print('hello\ahi')
print("Male\nFemale")
print('Ram\t\t500')
print('Shyam\t\t600')
print('Rsmnarayan\t800')
print('Ram\t500'.expandtabs(tabsize=15))
print('Shyam\t600'.expandtabs(tabsize=15))
print('Rsmnarayan\t800'.expandtabs(tabsize=15))
print(ord('\n'))
print(ord('a'))
print(ord('A'))
print(ord('@'))
print(ord('2'))
print(chr(65))
print(chr(97))
print(oct(ord('\n')))
print(hex(ord('\n')))
print(hex(ord('A')))
print('folder\nnewcar')
print('folder\012newcar')
print('folder\x0anewcar')
print(hex(ord('\t')))
print('folder\x09newcar')
print('Ram\t Rs 500')
#print('Ram\t \N {INDIAN RUPEE SIGN } 500')
print('Ram\t \u20b9 500')
print('Ram\t \U000020B9 500')
